version: "3.7"
services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - ./.var/postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    container_name: showroom-redis
    image: redis:6-alpine
    volumes:
    - ./.var/redis:/data
    ports:
    - "6379:6379"
  celery:
    container_name: showroom-celery
    build: .
    command: celery -A car_showroom worker -B
    volumes:
    - .:/app
    environment:
    - POSTGRES_HOST=postgres
    - REDIS_HOST=redis
    depends_on:
    - postgres
    - redis
  app:
    container_name: showroom-app
    build: .
    command: |
      gunicorn --workers=2 --bind=0.0.0.0:8000 car_showroom.wsgi:application
    volumes:
    - .:/app
    - ./config/staticfiles
    ports:
    - "8000:8000"
    environment:
    - POSTGRES_HOST=postgres
    depends_on:
    - postgres
    - celery
    - redis
  webserver:
    image: nginx:alpine
    container_name: showroom-nginx
    ports:
    - "80:80"
    volumes:
    - ./config/staticfiles
    - ./nginx.conf
    depends_on:
    - app
