# Generated by Django 4.1.6 on 2023-02-13 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier', '0001_initial'),
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellhistory',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_supplier', to='supplier.supplier'),
        ),
    ]
