# Generated by Django 4.1.5 on 2023-01-30 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car_showroom_app', '0001_initial'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsshowroom',
            name='cars_showroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier.car'),
        ),
        migrations.AddField(
            model_name='carsshowroom',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='supplier.supplier'),
        ),
        migrations.AddField(
            model_name='carshowroomsale',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_on_sale', to='supplier.car'),
        ),
        migrations.AddField(
            model_name='carshowroomsale',
            name='car_showroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showroom_sale', to='car_showroom_app.carshowroom'),
        ),
        migrations.AddField(
            model_name='carshowroom',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='car_showroom_app.location'),
        ),
    ]
