# Generated by Django 4.1.5 on 2023-01-30 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('car_showroom_app', '0001_initial'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsshowroom',
            name='cars_showroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier.car'),
        ),
        migrations.AddField(
            model_name='carshowroomsale',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_on_sale', to='supplier.car'),
        ),
        migrations.AddField(
            model_name='carshowroomsale',
            name='car_showroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showroom_sale', to='car_showroom_app.carshowroom'),
        ),
        migrations.AddField(
            model_name='carshowroom',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='car_showroom_app.location'),
        ),
        migrations.AddField(
            model_name='carshowroom',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='showroom_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
